version: "1.0"

services:
  app:
    container_name: new_ma7ata_app
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    depends_on:
      - db
    environment:
      - NODE_ENV=development


  db:
    container_name: new_ma7ata_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: new_ma7ata_dev
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:
